name: action_create test

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:11
      options: --user root
    steps:
    - uses: actions/checkout@v3
